import type { Metadata } from "next";
import "./globals.css";
import ResponsiveNav from "@/components/Navbar/ResponsiveNav";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider as NextThemesProvider } from "next-themes"
import { ThemeProvider } from "@/components/theme-provider"
// Import the localFont function from next/font/local
import localFont from 'next/font/local';

// Configure the font with its source files, weights, and styles
const customFont = localFont({
  src: [
    {
      path: '../public/fonts/dana-regular.woff',
      style: 'normal',
    },
    {
      path: '../public/fonts/dana-regular.woff2',
      style: 'normal',
    },
  ],
  variable: '--font-dana', // Define a CSS variable for the font
});

export const metadata: Metadata = {
  title: "API Website",
  description: "Generated by Shams",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" className={customFont.variable} suppressHydrationWarning>
      <body className="font-dana">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ResponsiveNav />
            {children}
            <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
